import { AreaDictionaly } from './area'

export const StationDictionaly = {
  JP1: {
    HBC: { name: 'ＨＢＣラジオ', ruby: 'えいちびーしーらじお' },
    STV: { name: 'ＳＴＶラジオ', ruby: 'えすてぃーびーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'AIR-G': { name: "AIR-G'（FM北海道）", ruby: 'えあーじーえふえむほっかいどう' },
    NORTHWAVE: { name: 'FM NORTH WAVE', ruby: 'えふえむのーすうぇーぶ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOIK: { name: 'NHKラジオ第1（札幌）', ruby: 'えぬえいちけーらじおだいいちさっぽろ' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP2: {
    RAB: { name: 'ＲＡＢ青森放送', ruby: 'あーるえーびーあおもりほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    AFB: { name: 'エフエム青森', ruby: 'えふえむあおもり' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP3: {
    IBC: { name: 'IBCラジオ', ruby: 'あいびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMI: { name: 'エフエム岩手', ruby: 'えふえむいわて' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP4: {
    TBC: { name: 'TBCラジオ', ruby: 'てぃーびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    DATEFM: { name: 'Date fm エフエム仙台', ruby: 'でーとえふえむえふえむせんだい' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP5: {
    ABS: { name: 'ＡＢＳ秋田放送', ruby: 'えーびーえすあきたほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    AFM: { name: 'エフエム秋田', ruby: 'えふえむあきた' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP6: {
    YBC: { name: 'YBC山形放送', ruby: 'わいびーしーやまがたほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    RFM: { name: 'Rhythm Station　エフエム山形', ruby: 'りずむすてーしょんえふえむやまがた' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP7: {
    RFC: { name: 'RFCラジオ福島', ruby: 'あーるえふしーらじおふくしま' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMF: { name: 'ふくしまFM', ruby: 'ふくしまえふえむ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOHK: { name: 'NHKラジオ第1（仙台）', ruby: 'えぬえいちけーらじおだいいちせんだい' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP8: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP9: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    CRT: { name: 'CRT栃木放送', ruby: 'しーあーるてぃーとちぎほうそう' },
    RADIOBERRY: { name: 'RADIO BERRY', ruby: 'らじおべりー' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP10: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    FMGUNMA: { name: 'FM GUNMA', ruby: 'えふえむぐんま' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP11: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP12: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP13: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP14: {
    TBS: { name: 'TBSラジオ', ruby: 'てぃーびーえすらじお' },
    QRR: { name: '文化放送', ruby: 'ぶんかほうそう' },
    LFR: { name: 'ニッポン放送', ruby: 'にっぽんほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    INT: { name: 'interfm', ruby: 'いんたーえふえむ' },
    FMT: { name: 'TOKYO FM', ruby: 'とーきょーえふえむ' },
    FMJ: { name: 'J-WAVE', ruby: 'じぇいうぇーぶ' },
    JORF: { name: 'ラジオ日本', ruby: 'らじおにっぽん' },
    BAYFM78: { name: 'BAYFM78', ruby: 'べいえふえむ' },
    NACK5: { name: 'NACK5', ruby: 'なっくふぁいぶ' },
    YFM: { name: 'ＦＭヨコハマ', ruby: 'えふえむよこはま' },
    IBS: { name: 'LuckyFM 茨城放送', ruby: 'らっきーえふえむいばらきほうそう' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP15: {
    BSN: { name: 'ＢＳＮラジオ', ruby: 'びーえすえぬらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMNIIGATA: { name: 'FM NIIGATA', ruby: 'えふえむにいがた' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP16: {
    KNB: { name: 'ＫＮＢラジオ', ruby: 'けーえぬびーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMTOYAMA: { name: 'ＦＭとやま', ruby: 'えふえむとやま' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP17: {
    MRO: { name: 'MROラジオ', ruby: 'えむあーるおーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    HELLOFIVE: { name: 'エフエム石川', ruby: 'えふえむいしかわ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP18: {
    FBC: { name: 'FBCラジオ', ruby: 'えふびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMFUKUI: { name: 'FM福井', ruby: 'えふえむふくい' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP19: {
    YBS: { name: 'ＹＢＳラジオ', ruby: 'わいびーえすらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'FM-FUJI': { name: 'FM FUJI', ruby: 'えふえむふじ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP20: {
    SBC: { name: 'SBCラジオ', ruby: 'えすびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMN: { name: 'ＦＭ長野', ruby: 'えふえむながの' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOAK: { name: 'NHKラジオ第1（東京）', ruby: 'えぬえいちけーらじおだいいちとうきょう' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP21: {
    CBC: { name: 'CBCラジオ', ruby: 'しーびーしーらじお' },
    TOKAIRADIO: { name: 'TOKAI RADIO', ruby: 'とうかいらじお' },
    GBS: { name: 'ぎふチャン', ruby: 'ぎふちゃん' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'ZIP-FM': { name: 'ZIP-FM', ruby: 'じっぷえふえむ' },
    FMGIFU: { name: 'ＦＭ ＧＩＦＵ', ruby: 'えふえむぎふ' },
    FMAICHI: { name: 'FM AICHI', ruby: 'えふえむあいち' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP22: {
    SBS: { name: 'SBSラジオ', ruby: 'えすびーえすらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'K-MIX': { name: 'K-MIX', ruby: 'けいみっくす' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP23: {
    CBC: { name: 'CBCラジオ', ruby: 'しーびーしーらじお' },
    TOKAIRADIO: { name: 'TOKAI RADIO', ruby: 'とうかいらじお' },
    GBS: { name: 'ぎふチャン', ruby: 'ぎふちゃん' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'ZIP-FM': { name: 'ZIP-FM', ruby: 'じっぷえふえむ' },
    FMAICHI: { name: 'FM AICHI', ruby: 'えふえむあいち' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP24: {
    CBC: { name: 'CBCラジオ', ruby: 'しーびーしーらじお' },
    TOKAIRADIO: { name: 'TOKAI RADIO', ruby: 'とうかいらじお' },
    GBS: { name: 'ぎふチャン', ruby: 'ぎふちゃん' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'ZIP-FM': { name: 'ZIP-FM', ruby: 'じっぷえふえむ' },
    FMMIE: { name: 'レディオキューブ ＦＭ三重', ruby: 'れでぃおきゅーぶえふえむみえ' },
    FMAICHI: { name: 'FM AICHI', ruby: 'えふえむあいち' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOCK: { name: 'NHKラジオ第1（名古屋）', ruby: 'えぬえいちけーらじおだいいちなごや' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP25: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    KBS: { name: 'KBS京都ラジオ', ruby: 'けーびーえすきょうとらじお' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    'E-RADIO': { name: 'e-radio FM滋賀', ruby: 'いーらじおえふえむしが' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    'ALPHA-STATION': { name: 'α-STATION FM KYOTO', ruby: 'あるふぁすてーしょんえふえむきょうと' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP26: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    KBS: { name: 'KBS京都ラジオ', ruby: 'けーびーえすきょうとらじお' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    'ALPHA-STATION': { name: 'α-STATION FM KYOTO', ruby: 'あるふぁすてーしょんえふえむきょうと' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP27: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    KBS: { name: 'KBS京都ラジオ', ruby: 'けーびーえすきょうとらじお' },
    'ALPHA-STATION': { name: 'α-STATION FM KYOTO', ruby: 'あるふぁすてーしょんえふえむきょうと' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP28: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP29: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    'ALPHA-STATION': { name: 'α-STATION FM KYOTO', ruby: 'あるふぁすてーしょんえふえむきょうと' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP30: {
    '802': { name: 'FM802', ruby: 'えふえむはちまるに' },
    ABC: { name: 'ABCラジオ', ruby: 'えーびーしーらじお' },
    MBS: { name: 'MBSラジオ', ruby: 'えむびーえすらじお' },
    OBC: { name: 'OBCラジオ大阪', ruby: 'おーびーしーらじおおおさか' },
    CCL: { name: 'FM COCOLO', ruby: 'えふえむこころ' },
    FMO: { name: 'FM大阪', ruby: 'えふえむおおさか' },
    WBS: { name: 'wbs和歌山放送', ruby: 'だぶりゅーびーえすわかやまほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    KISSFMKOBE: { name: 'Kiss FM KOBE', ruby: 'きっすえふえむこうべ' },
    CRK: { name: 'ラジオ関西', ruby: 'しーあるけーらじおかんさい' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOBK: { name: 'NHKラジオ第1（大阪）', ruby: 'えぬえいちけーらじおだいいちおおさか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP31: {
    BSS: { name: 'BSSラジオ', ruby: 'びーえすえすらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'FM-SANIN': { name: 'エフエム山陰', ruby: 'えふえむさんいん' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOFK: { name: 'NHKラジオ第1（広島）', ruby: 'えぬえいちけーらじおだいいちひろしま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP32: {
    BSS: { name: 'BSSラジオ', ruby: 'びーえすえすらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'FM-SANIN': { name: 'エフエム山陰', ruby: 'えふえむさんいん' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOFK: { name: 'NHKラジオ第1（広島）', ruby: 'えぬえいちけーらじおだいいちひろしま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP33: {
    RSK: { name: 'ＲＳＫラジオ', ruby: 'あーるえすけーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'FM-OKAYAMA': { name: 'ＦＭ岡山', ruby: 'えふえむおかやま' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOFK: { name: 'NHKラジオ第1（広島）', ruby: 'えぬえいちけーらじおだいいちひろしま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP34: {
    RCC: { name: 'RCCラジオ', ruby: 'あーるしーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    HFM: { name: '広島FM', ruby: 'ひろしまえふえむ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOFK: { name: 'NHKラジオ第1（広島）', ruby: 'えぬえいちけーらじおだいいちひろしま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP35: {
    KRY: { name: 'ＫＲＹ山口放送', ruby: 'けーあーるわいやまぐちほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMY: { name: 'エフエム山口', ruby: 'えふえむやまぐち' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOFK: { name: 'NHKラジオ第1（広島）', ruby: 'えぬえいちけーらじおだいいちひろしま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP36: {
    JRT: { name: 'ＪＲＴ四国放送', ruby: 'じぇいあーるてぃーしこくほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FM807: { name: 'FM徳島', ruby: 'えふえむとくしま' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOZK: { name: 'NHKラジオ第1（松山）', ruby: 'えぬえいちけーらじおだいいちまつやま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP37: {
    RNC: { name: 'RNC西日本放送', ruby: 'あーるえぬしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMKAGAWA: { name: 'エフエム香川', ruby: 'えふえむかがわ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOZK: { name: 'NHKラジオ第1（松山）', ruby: 'えぬえいちけーらじおだいいちまつやま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP38: {
    RNB: { name: 'RNB南海放送', ruby: 'あーるえぬびーなんかいほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'JOEU-FM': { name: 'FM愛媛', ruby: 'えふえむえひめ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOZK: { name: 'NHKラジオ第1（松山）', ruby: 'えぬえいちけーらじおだいいちまつやま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP39: {
    RKC: { name: 'RKC高知放送', ruby: 'あーるけーしーこうちほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    'HI-SIX': { name: 'エフエム高知', ruby: 'えふえむこうち' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOZK: { name: 'NHKラジオ第1（松山）', ruby: 'えぬえいちけーらじおだいいちまつやま' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP40: {
    RKB: { name: 'RKBラジオ', ruby: 'あーるけーびーらじお' },
    KBC: { name: 'KBCラジオ', ruby: 'けーびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    LOVEFM: { name: 'LOVE FM', ruby: 'らぶえふえむ' },
    CROSSFM: { name: 'CROSS FM', ruby: 'くろすえふえむ' },
    FMFUKUOKA: { name: 'FM FUKUOKA', ruby: 'えふえむふくおか' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP41: {
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMS: { name: 'エフエム佐賀', ruby: 'えふえむさが' },
    NBC: { name: 'NBCラジオ', ruby: 'えぬびーしーらじお' },
    RKB: { name: 'RKBラジオ', ruby: 'あーるけーびーらじお' },
    KBC: { name: 'KBCラジオ', ruby: 'けーびーしーらじお' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP42: {
    NBC: { name: 'NBCラジオ', ruby: 'えぬびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMNAGASAKI: { name: 'FM長崎', ruby: 'えふえむながさき' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP43: {
    RKK: { name: 'RKKラジオ', ruby: 'あーるけーけーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FMK: { name: 'FMKエフエム熊本', ruby: 'えふえむけーえふえむくまもと' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP44: {
    OBS: { name: 'OBSラジオ', ruby: 'おーびーえすらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FM_OITA: { name: 'エフエム大分', ruby: 'えふえむおおいた' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP45: {
    MRT: { name: '宮崎放送', ruby: 'みやざきほうそう' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    JOYFM: { name: 'エフエム宮崎', ruby: 'えふえむみやざき' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP46: {
    MBC: { name: 'ＭＢＣラジオ', ruby: 'えむびーしーらじお' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    MYUFM: { name: 'μＦＭ', ruby: 'みゅーえふえむ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  },
  JP47: {
    RBC: { name: 'RBCiラジオ', ruby: 'あーるびーしーあいらじお' },
    ROK: { name: 'ラジオ沖縄', ruby: 'らじおおきなわ' },
    RN1: { name: 'ラジオNIKKEI第1', ruby: 'らじおにっけいだいいち' },
    RN2: { name: 'ラジオNIKKEI第2', ruby: 'らじおにっけいだいに' },
    FM_OKINAWA: { name: 'FM沖縄', ruby: 'えふえむおきなわ' },
    'HOUSOU-DAIGAKU': { name: '放送大学', ruby: 'ほうそうだいがく' },
    JOLK: { name: 'NHKラジオ第1（福岡）', ruby: 'えぬえいちけーらじおだいいちふくおか' },
    'JOAK-FM': { name: 'NHK-FM（東京）', ruby: 'えぬえいちけーえふえむとうきょう' }
  }
} as const satisfies Record<AreaDictionaly, Record<string, Station>>

type Station = { name: string; ruby: string }
